import {Router} from 'express'; import {z} from 'zod'; import {pool} from '../config/db.js'; import {asyncHandler,ok,HttpError} from '../utils/http.js'; import {requireAuth} from '../middleware/auth.js';
const r=Router();r.use(requireAuth);
// V48: was returning only {id,created_at,last_message_at} — no counterparty
// name, no message preview, no unread count. The frontend (sellerChatApi in
// features/seller/sellerApi.ts, used by Buyer/SellerMessagesScreen) always
// needed item.other_user.name / item.last_message_preview / item.unread_count
// to render a usable conversation list; none of those existed, so every row
// silently fell back to generic "Vendeur"/"Client" placeholders.
r.get('/conversations',asyncHandler(async(req,res)=>ok(res,(await pool.query(`SELECT c.id,c.created_at,coalesce(lm.created_at,c.created_at) last_message_at,lm.content last_message_preview,ou.id other_user_id,ou.name other_user_name,ou.role other_user_role,(SELECT count(*)::int FROM messages um WHERE um.conversation_id=c.id AND um.sender_id!=$1 AND um.created_at>coalesce(cm.last_read_at,'-infinity'::timestamptz)) unread_count FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id AND cm.user_id=$1 LEFT JOIN conversation_members ocm ON ocm.conversation_id=c.id AND ocm.user_id!=$1 LEFT JOIN users ou ON ou.id=ocm.user_id LEFT JOIN LATERAL (SELECT content,created_at FROM messages m2 WHERE m2.conversation_id=c.id ORDER BY m2.created_at DESC LIMIT 1) lm ON true ORDER BY last_message_at DESC`,[req.user.sub])).rows.map(row=>({id:row.id,created_at:row.created_at,last_message_at:row.last_message_at,last_message_preview:row.last_message_preview,unread_count:row.unread_count,other_user:row.other_user_id?{id:row.other_user_id,name:row.other_user_name,role:row.other_user_role}:null})))));
r.post('/conversations',asyncHandler(async(req,res)=>{const s=z.object({user_id:z.string().uuid()}).parse(req.body);if(s.user_id===req.user.sub)throw new HttpError(422,'Conversation invalide');const c=await pool.connect();try{await c.query('BEGIN');const existing=(await c.query(`SELECT c.id FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id AND a.user_id=$1 JOIN conversation_members b ON b.conversation_id=c.id AND b.user_id=$2 WHERE (SELECT count(*) FROM conversation_members x WHERE x.conversation_id=c.id)=2 LIMIT 1`,[req.user.sub,s.user_id])).rows[0];if(existing){await c.query('COMMIT');return ok(res,existing)}const cv=(await c.query('INSERT INTO conversations DEFAULT VALUES RETURNING id,created_at')).rows[0];await c.query('INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2),($1,$3)',[cv.id,req.user.sub,s.user_id]);await c.query('COMMIT');ok(res,cv,201)}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
r.get('/conversations/:id/messages',asyncHandler(async(req,res)=>{const member=(await pool.query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.sub])).rowCount;if(!member)throw new HttpError(403,'Conversation non autorisée');ok(res,(await pool.query('SELECT id,sender_id,content,created_at FROM messages WHERE conversation_id=$1 ORDER BY created_at DESC LIMIT 100',[req.params.id])).rows.reverse())}));
r.post('/conversations/:id/read',asyncHandler(async(req,res)=>{const row=(await pool.query('UPDATE conversation_members SET last_read_at=now() WHERE conversation_id=$1 AND user_id=$2 RETURNING conversation_id,last_read_at',[req.params.id,req.user.sub])).rows[0];if(!row)throw new HttpError(403,'Conversation non autorisée');ok(res,row)}));
r.post('/conversations/:id/messages',asyncHandler(async(req,res)=>{const s=z.object({content:z.string().min(1).max(5000)}).parse(req.body);const member=(await pool.query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.sub])).rowCount;if(!member)throw new HttpError(403,'Conversation non autorisée');const row=(await pool.query('INSERT INTO messages(conversation_id,sender_id,content) VALUES($1,$2,$3) RETURNING id,sender_id,content,created_at',[req.params.id,req.user.sub,s.content])).rows[0];ok(res,row,201)}));
export default r;
