CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), phone citext UNIQUE NOT NULL, email citext UNIQUE, name varchar(120) NOT NULL,
 password_hash text, role varchar(20) NOT NULL CHECK(role IN ('client','vendor','transporter','admin')),
 status varchar(20) NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','banned','pending')),
 phone_verified boolean NOT NULL DEFAULT false, email_verified boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX users_role_idx ON users(role); CREATE INDEX users_status_idx ON users(status);
CREATE TABLE auth_refresh_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, jti uuid UNIQUE NOT NULL, token_hash char(64) UNIQUE NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, ip_address inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX refresh_user_idx ON auth_refresh_tokens(user_id,expires_at);
CREATE TABLE auth_otp_challenges(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),phone citext NOT NULL,code_hash char(64) NOT NULL,purpose varchar(30) NOT NULL,attempts int NOT NULL DEFAULT 0,max_attempts int NOT NULL DEFAULT 5,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX otp_phone_idx ON auth_otp_challenges(phone,created_at DESC);
CREATE TABLE user_addresses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,label varchar(80),recipient_name varchar(120) NOT NULL,phone varchar(30) NOT NULL,address_line text NOT NULL,city varchar(100) NOT NULL,region varchar(100),country char(2) NOT NULL DEFAULT 'ML',latitude numeric(9,6),longitude numeric(9,6),is_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vendors(id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,shop_name varchar(160) NOT NULL,slug citext UNIQUE NOT NULL,kyc_status varchar(20) NOT NULL DEFAULT 'pending',certified_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE transporters(id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,kyc_status varchar(20) NOT NULL DEFAULT 'pending',availability varchar(20) NOT NULL DEFAULT 'offline',vehicle_type varchar(80),vehicle_plate varchar(40),certified_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE kyc_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,document_type varchar(50) NOT NULL,file_key text NOT NULL,status varchar(20) NOT NULL DEFAULT 'pending',reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz,rejection_reason text,created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE wallets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,currency char(3) NOT NULL DEFAULT 'XOF',available_amount bigint NOT NULL DEFAULT 0 CHECK(available_amount>=0),locked_amount bigint NOT NULL DEFAULT 0 CHECK(locked_amount>=0),status varchar(20) NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_accounts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code varchar(80) UNIQUE NOT NULL,name varchar(160) NOT NULL,type varchar(30) NOT NULL CHECK(type IN ('asset','liability','revenue','expense','clearing')),currency char(3) NOT NULL DEFAULT 'XOF',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference varchar(120) UNIQUE NOT NULL,type varchar(50) NOT NULL,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_entries(id bigserial PRIMARY KEY,transaction_id uuid NOT NULL REFERENCES ledger_transactions(id),account_id uuid NOT NULL REFERENCES ledger_accounts(id),amount bigint NOT NULL CHECK(amount<>0),currency char(3) NOT NULL DEFAULT 'XOF',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ledger_entries_account_idx ON ledger_entries(account_id,created_at);
INSERT INTO ledger_accounts(code,name,type) VALUES('partner_clearing_xof','Fonds réels chez partenaire - clearing','clearing'),('livi_customer_liability_xof','Passif soldes clients LIVI','liability'),('livi_vendor_payable_xof','Dettes vendeurs','liability'),('livi_transporter_payable_xof','Dettes transporteurs','liability'),('livi_fee_revenue_xof','Commissions LIVI','revenue') ON CONFLICT DO NOTHING;

CREATE TABLE categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar(100) UNIQUE NOT NULL,slug citext UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),vendor_id uuid NOT NULL REFERENCES users(id),category_id uuid REFERENCES categories(id),name varchar(200) NOT NULL,slug citext UNIQUE NOT NULL,description text,price_xof bigint NOT NULL CHECK(price_xof>0),stock integer NOT NULL DEFAULT 0 CHECK(stock>=0),status varchar(20) NOT NULL DEFAULT 'active' CHECK(status IN ('draft','active','paused','archived')),search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple',coalesce(name,'')||' '||coalesce(description,''))) STORED,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX products_search_idx ON products USING gin(search_vector); CREATE INDEX products_vendor_idx ON products(vendor_id,status);
CREATE TABLE product_media(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,file_key text NOT NULL,kind varchar(20) NOT NULL DEFAULT 'image',sort_order int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE wishlists(user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,product_id));
CREATE TABLE reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES products(id),user_id uuid NOT NULL REFERENCES users(id),rating int NOT NULL CHECK(rating BETWEEN 1 AND 5),comment text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(product_id,user_id));

CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),buyer_id uuid NOT NULL REFERENCES users(id),vendor_id uuid NOT NULL REFERENCES users(id),status varchar(30) NOT NULL DEFAULT 'pending_payment',subtotal_amount bigint NOT NULL CHECK(subtotal_amount>=0),shipping_fee bigint NOT NULL DEFAULT 0 CHECK(shipping_fee>=0),total_amount bigint NOT NULL CHECK(total_amount>=0),currency char(3) NOT NULL DEFAULT 'XOF',delivery_address_id uuid NOT NULL REFERENCES user_addresses(id),paid_at timestamptz,delivered_at timestamptz,cancelled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX orders_buyer_idx ON orders(buyer_id,created_at); CREATE INDEX orders_vendor_idx ON orders(vendor_id,created_at); CREATE INDEX orders_status_idx ON orders(status);
CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id uuid NOT NULL REFERENCES products(id),quantity int NOT NULL CHECK(quantity>0),unit_price bigint NOT NULL CHECK(unit_price>0),total_price bigint NOT NULL CHECK(total_price>0));
CREATE TABLE escrow_transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid UNIQUE NOT NULL REFERENCES orders(id),buyer_id uuid NOT NULL REFERENCES users(id),vendor_id uuid NOT NULL REFERENCES users(id),amount bigint NOT NULL CHECK(amount>0),shipping_fee bigint NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'awaiting_payment' CHECK(status IN ('awaiting_payment','payment_pending','funded','released','refunded','disputed','cancelled')),payment_reference varchar(120) UNIQUE,funded_at timestamptz,released_at timestamptz,refunded_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX escrow_buyer_idx ON escrow_transactions(buyer_id,created_at); CREATE INDEX escrow_vendor_idx ON escrow_transactions(vendor_id,created_at);

CREATE TABLE shipments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid UNIQUE NOT NULL REFERENCES orders(id),transporter_id uuid REFERENCES users(id),status varchar(30) NOT NULL DEFAULT 'pending',tracking_code varchar(80) UNIQUE,qr_secret_hash char(64),pickup_at timestamptz,delivered_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE shipment_events(id bigserial PRIMARY KEY,shipment_id uuid NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,status varchar(40) NOT NULL,latitude numeric(9,6),longitude numeric(9,6),note text,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE disputes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id),opened_by uuid NOT NULL REFERENCES users(id),status varchar(20) NOT NULL DEFAULT 'open',reason text NOT NULL,resolution text,resolved_by uuid REFERENCES users(id),resolved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispute_evidence(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),dispute_id uuid NOT NULL REFERENCES disputes(id) ON DELETE CASCADE,uploaded_by uuid NOT NULL REFERENCES users(id),file_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conversation_members(conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,last_read_at timestamptz,PRIMARY KEY(conversation_id,user_id));
CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,sender_id uuid NOT NULL REFERENCES users(id),content text NOT NULL CHECK(length(content)<=5000),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX messages_conv_idx ON messages(conversation_id,created_at);
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,type varchar(50) NOT NULL,title varchar(160) NOT NULL,body text,data jsonb NOT NULL DEFAULT '{}'::jsonb,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX notifications_user_idx ON notifications(user_id,created_at DESC);
CREATE TABLE audit_logs(id bigserial PRIMARY KEY,actor_user_id uuid REFERENCES users(id),action varchar(100) NOT NULL,entity_type varchar(80) NOT NULL,entity_id uuid,request_id varchar(120),ip_address inet,user_agent text,before_data jsonb,after_data jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_entity_idx ON audit_logs(entity_type,entity_id,created_at); CREATE INDEX audit_actor_idx ON audit_logs(actor_user_id,created_at);
CREATE TABLE idempotency_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES users(id),key varchar(200) NOT NULL,request_hash char(64) NOT NULL,response_status int,response_body jsonb,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,UNIQUE(user_id,key));
CREATE TABLE partner_payment_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),provider varchar(50) NOT NULL,event_id varchar(160) NOT NULL,payload jsonb NOT NULL,signature_valid boolean NOT NULL DEFAULT false,processed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(provider,event_id));
CREATE OR REPLACE FUNCTION prevent_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Ledger entries are immutable'; END; $$;
CREATE TRIGGER ledger_transactions_no_update BEFORE UPDATE OR DELETE ON ledger_transactions FOR EACH ROW EXECUTE FUNCTION prevent_ledger_mutation();
CREATE TRIGGER ledger_entries_no_update BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION prevent_ledger_mutation();
