import assert from 'node:assert/strict';
import { PREPARATION_OPTIONS_HOURS, SHELF_LIFE_REFERENCE_TYPES, calculateIntercityGuaranteeXof, calculateIntercityTransportCostXof, calculateIntercityShipping, assertPerishableCompatible } from './logisticsTiming.js';
assert.deepEqual(PREPARATION_OPTIONS_HOURS,[1,2,3,4,12,24]);
assert.deepEqual(SHELF_LIFE_REFERENCE_TYPES,['harvest','production','packaging','preparation']);
assert.equal(calculateIntercityGuaranteeXof(500,{guarantee_bps:1000}),50n);
assert.equal(calculateIntercityGuaranteeXof(3333,{guarantee_bps:1000}),334n);
assert.equal(calculateIntercityTransportCostXof({fuel_cost_xof:300,operating_charges_xof:200,partner_service_fee_xof:100},1000),1600n);
assert.equal(calculateIntercityShipping({transportCostXof:1600,guaranteeXof:9999}),1600n);
assert.doesNotThrow(()=>assertPerishableCompatible({is_perishable:true,shelf_life_hours:24,shelf_life_reference_type:'preparation',preparation_time_hours:4},4,120,new Date('2026-01-01T10:00:00Z')));
console.log('V59 pure logistics checks: PASS');
